### ISSUE TITLE
Show list of rooms with more than 5 rooms/page

### ISSUE THREAD

**Issue by 00100200345** [helpwave/helpwave#107]
when creating a new ward, the list of rooms shows 5 rooms only. Often, wards have more rooms so that navigation is clumsy.

**Comment by MaxSchaefer** [comment]
Seams fixed? @00100200345 

https://github.com/user-attachments/assets/f07c5d4e-cdef-4a23-8e42-92c4fa400580

**Comment by 00100200345** [comment]
The wording of the initial issue was poor. We know that more rooms can be created, what was meant is that only 5 rooms are shown and then you have to go to a second page. This is a nuisance and looking at how the space is used on the page (roughly 1/3 is dedicated to the list of rooms, the rest contains rather little relevant information), we thought, a more compact or scrollable list would be useful.
