### ISSUE TITLE
Tbd: change task status from "unschedulded/in progress/done" to e.g. "Todo/done"

### ISSUE THREAD

**Issue by 00100200345** [helpwave/helpwave#123]
what: we are unsure, if the three separate status "unschedulded/in progress/done" are really necessary in a clinical setting. We should discuss, whether a simple distinction between the todo and the finished tasks is more appropriate and uncluttered

why: usability

**Comment by sophiafe** [comment]
Same issue as #129 tasks alternative to kanban.
